### ISSUE TITLE
LispWorks on Windows

### ISSUE THREAD

**Issue by priyadarshan** [podiki/cl-tcod-tutorial#5]
I would like very much to go through your cl-tcod tutorial using my platform, LispWorks on WIndows.
 
I see [libtocd](https://github.com/libtcod/libtcod#using-one-of-our-downloads) is available on Windows. Would you reckon the tutorial is easily portable to LispWorks? Would you be available, your time permitting of course, to assist in case of LispWorks or Windows-side issues?

**Comment by priyadarshan** [comment]
Let me first investigate this myself. If I may, I will reopen if needed.

**Comment by podiki** [comment]
Hi @priyadarshan, thanks for your interest. I don't currently use Windows (and have never tried LispWorks), but hopefully everything is pretty portable if you have libtcod, quicklisp, and my fork of cl-tcod. I can try to help you debug as needed, but not sure how much help I can be.

Do report back however it goes and I can update the readme.
